# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
#[it]
languageCode = "it"
contentDir = "content/it"
title = "Gloria Gori (it)"
[it.params]
description = "La mia pagina web"
[[it.menu.main]]
name = "About"
url = "#about"
weight = 1
